[tool.black]
target-version = ["py310", "py311"]
single-quotes = true

[tool.isort]
profile = "black"
combine_as_imports = true
combine_star = true

[tool.coverage.report]
exclude_lines = [
    "if TYPE_CHECKING:",
]

[tool.mypy]
strict = true
pretty = true
incremental = true
python_version = 3.11